version: '3'
services:
  mysql-wordpress:
    container_name: mysql-wordpress
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  wordpress:
    container_name: wordpress
    depends_on:
      - mysql-wordpress
      - traefik
    image: wordpress:latest
    volumes: 
      - wordpress-data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql-wordpress:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=(Host(`www.dominio.com.br`) || Host(`dominio.com.br`))"
      - "traefik.http.routers.site.tls"
      - "traefik.http.routers.site.tls.certresolver=le"
      - "traefik.http.routers.site.middlewares=site-redirect@docker,site-compress@docker"
      - "traefik.http.services.site.loadbalancer.server.port=80"
      - "traefik.http.middlewares.site-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.site-compress.compress=true"
  traefik:
    image: "traefik:v2.0.7"
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/config/dynamic.toml"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--accesslog.format=common"
      - "--metrics.prometheus=true"
      - "--certificatesResolvers.le.acme.email=email@dominio.com"
      - "--certificatesResolvers.le.acme.storage=acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.dominio.com.br`)"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.tls.certresolver=le"
        - "traefik.http.routers.traefik.middlewares=traefik-compress@docker,traefik-auth@docker"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.traefik-compress.compress=true"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=manager:$$apr1$$KMNMV5k1$$FAHcGgMowUipkhVINbj5O/"
        - "traefik.http.middlewares.traefik-auth.basicauth.realm=Dashboard"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
volumes:
  mysql-data:
  wordpress-data:
